import Head from 'next/head';
import Image from 'next/legacy/image';
import { Navbar, Header, Footer } from '../../common';
import { FunctionComponent, PropsWithChildren } from 'react';

const BaseLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
	return (
		<>
			<div className='pb-16 mx-auto max-w-7xl px-4 space-y-8 sm:px-6 lg:px-8'>
				<Head>
					<title>VeriDID</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<div className='relative'>
					<div className='relative z-10 bg-white pb-8 sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32'>
						<Navbar />
						<Header />
					</div>
					<div className='relative lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2'>
						{/* <Image
							priority
							layout='responsive'
							width='1440'
							height='613'
							alt=''
							className='sm:h-72 md:h-96 '
							src='https://assets-global.website-files.com/5dfc18aeef0cf9644ab5ccca/617834b727b4573c6718b5a5_kaleidoscope-hexagon-shapes.svg'
						/> */}
					</div>
				</div>

				{children}
			</div>
			<Footer />
		</>
	);
};

export default BaseLayout;
